language: python

sudo: false

python:
  - "2.7"

install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas scipy matplotlib scikit-learn
  - source activate testenv
  - pip install git+https://github.com/neurolearn/pyneurovault_upload
  - pip install python-coveralls
  - pip install -r requirements.txt
  - python setup.py install

script: coverage run --source nltools -m py.test

after_success:
  - coveralls
